settings:
  name: "StorageGRID 11.5"
  search: "storagegrid-enable,storagegrid-115"
  downlevel: true
  internal:
    pdf_enabled: false
  prod:
    pdf_enabled: true
    harmony_enabled: true
    lipi_enabled: false
  versions:
    - version-number: "11.5"
      url: /storagegrid-115
    - version-number: "11.9"
      url: /storagegrid
    - version-number: "11.8"
      url: /storagegrid-118         
    - version-number: "11.7"
      url: /storagegrid-117     
    - version-number: "11.6" 
      url: /storagegrid-116   
sidebar:
  entries:
    - title: StorageGRID 11.5 Docs
      url: /index.html
    - section: release-notes
    - title: Get started
      entries:
      - section: primer
      - section: network
    - title: Install and upgrade software
      entries:
      - section: rhel
      - section: ubuntu
      - section: vmware
      - section: upgrade
    - title: Install and maintain hardware
      entries:
      - section: sg6000
      - section: sg5700
      - section: sg5600
      - section: sg100-1000
    - title: Configure and manage
      entries:  
      - section: admin
      - section: ilm
      - section: harden
      - section: fabricpool
    - title: Use StorageGRID
      entries: 
      - section: tenant
      - section: s3
      - section: swift
    - title: Monitor and troubleshoot
      entries:  
      - section: monitor  
      - section: troubleshoot
      - section: audit
    - title: Maintain
      entries:
      - section: expand
      - section: maintain
    - title:  Legacy versions
      url: /earlier-versions.html
    - title: Legal notices
      url: /legal-notices.html 
product-family:
  name: StorageGRID documentation
  repo: storagegrid-family