sidebar:
  entries:
    - title: StorageGRID 11.5 Docs
      url: /index.html
    - section: primer
    - section: network
    - section: sg100-1000
    - section: sg5600
    - section: sg5700
    - section: sg6000
    - section: vmware
    - section: rhel
    - section: ubuntu
    - section: upgrade
    - section: admin
    - section: ilm
    - section: harden
    - section: fabricpool
    - section: tenant
    - section: s3
    - section: swift
    - section: monitor
    - section: expand
    - section: maintain
    - section: audit




homepage:
  tiles:
    - title: Get started
      links:
      - title: Grid primer
        url: /primer/primer_overview.html
      - title: Network guidelines
        url: /network/index.html
    - title: Install & maintain hardware
      links:
      - title: SG100 & SG1000 services appliances
        url: /sg100-1000/index.html
      - title: SG6000 storage appliances
        url: /sg6000/index.html
      - title: SG5700 storage appliances
        url: /sg5700/index.html
      - title: SG5600 storage appliances
        url: /sg5600/index.html
    - title: Install & upgrade software
      links:
      - title: VMware
        url: /vmware/index.html
      - title: Red Hat Enterprise Linux or CentOS
        url: /rhel/index.html
      - title: Ubuntu or Debian
        url: /ubuntu/index.html
      - title: Upgrade
        url: /upgrade/index.html
    - title: Configure the grid
      links:
      - title: Administer
        url: /admin/index.html
      - title: Create ILM rules & policy
        url: /ilm/index.html
      - title: System hardening
        url: /harden/index.html
      - title: Integrate FabricPool
        url: /fabricpool/index.html
    - title: Manage objects
      links:
      - title: Use a tenant account
        url: /tenant/index.html
      - title: Use S3
        url: /s3/index.html
      - title: Use Swift
        url: /swift/index.html
    - title: Monitor & maintain
      links:
      - title: Monitor & troubleshoot
        url: /monitor/index.html
      - title: Expand
        url: /expand/index.html
      - title: Maintain & recover
        url: /maintain/index.html
      - title: Review audit logs
        url: /audit/index.html
