sidebar:
  entries:
    - title: StorageGRID Documentation
      url: /index.html
    - section: primer
    - section: admin
    - section: audit
    - section: expand
    - section: fabricpool
    - section: harden
    - section: ilm
    - section: maintain
    - section: monitor
    - section: network
    - section: rhel
    - section: s3
    - section: sg100-1000
    - section: sg5600
    - section: sg5700
    - section: sg6000
    - section: swift
    - section: tenant
    - section: ubuntu
    - section: upgrade
    - section: vmware

homepage:
  tiles:
    - title: Get started
      links:
      - title: Grid primer
        url: /primer/index.html
      - title: Network guidelines
        url: /network/index.html
    - title: Install & maintain hardware
      links:
      - title: SG100 & SG1000 services appliances
        url: /sg100-1000/index.html
      - title: SG6000 storage appliances
        url: /sg6000/index.html
      - title: SG5700 storage appliances
        url: /sg5700/index.html
      - title: SG56 storage appliances
        url: /sg5600/index.html
