sidebar:
  entries:
    - title: StorageGRID Documentation
      url: /index.html
    - section: admin
    - section: audit
    - section: expand
    - section: fabricpool
    - section: harden
    - section: ilm
    - section: maintain
    - section: monitor
    - section: network
    - section: primer
    - section: rhel
    - section: s3
    - section: sg100-1000
    - section: sg5600
    - section: sg5700
    - section: sg6000
    - section: swift
    - section: tenant
    - section: ubuntu
    - section: upgrade
    - section: vmware

homepage:
  tiles:
    - title: This is the title of a tile
      links:
      - title: This is the title of a link
        summary: This is optional and no longer common
        url: /admin/index.html
