sidebar:
  entries:
    - title: StorageGRID Documentation
      url: "/index.html"
    - section: admin
    - section: audit
    - section: expand
    - section: fabricpool
    - section: harden
    - section: ilm
    - section: maintain
    - section: monitor
    - section: network
    - section: primer
    - section: rhel
    - section: s3
    - section: sg100-1000
    - section: sg5600
    - section: sg5700
    - section: sg6000
    - section: swift
    - section: tenant
    - section: ubuntu
    - section: upgrade
    - section: vmware

homepage:
  tiles:
